ignore:
  - "**/.venv"
  - "**/_old"
  - "**/*_pb2*.py"
  - "**/*.pb.go"
  - "**/*_pb*.js"
  - "**/*_pb*.ts"
  - "**/data.ts"
  - "**/cog_settings.py"
  - "**/CogSettings.d.ts"
  - "**/CogSettings.js"
  - "**/CogTypes.d.ts"
  - "**/node_modules"
  - "**/build"
license:
  CopyrightYear: 2023
  Author: "AI Redefined Inc. <dev+cogment@ai-r.com>"
