ignore:
  - "?eggs"
  - "**/__pycache__"
  - "**/cogment_*.yaml"
  - "**/*_pb2*.py"
  - "**/*.pb.go"
  - "**/*_pb*.js"
  - "**/*_pb*.ts"
  - "**/data.ts"
  - "**/cog_settings.py"
  - "**/CogSettings.d.ts"
  - "**/CogSettings.js"
  - "**/third_party"
  - "*/cogment/api"
  - "**/htmlcov"
  - "**/node_modules"
  - "web_client/build"
  - "**/pybullet_driving_env/*"
license:
  CopyrightYear: 2021
  Author: "AI Redefined Inc. <dev+cogment@ai-r.com>"
