stages:
  - build
  - lint
  - test

.base:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    # Installation instructions from https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
    - curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - apt-get install -y nodejs
    - pip install virtualenv
    - npm ci --cache .npm --prefer-offline
  cache:
    # pip's cache
    - paths:
        - .cache/pip
        - "**/.venv"
    # npm's cache
    - key:
        files:
          - web_client/package-lock.json
      paths:
        - .npm/

build:
  extends: .base
  stage: build
  script:
    - ./run.sh build

apache_licenses_check:
  stage: lint
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker

lint:
  extends: .base
  stage: lint
  script:
    - ./run.sh lint

test:
  extends: .base
  stage: lint
  script:
    - ./run.sh test
