.base:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    NPM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/npm"
  before_script:
    - mkdir -p ${PIP_CACHE_DIR}
    - mkdir -p ${NPM_CACHE_DIR}
    # Installation instructions from https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get update && apt-get install -y software-properties-common && apt-add-repository non-free && apt-get update
    - apt-get install -y nodejs swig unrar python3-opencv
    - pip install virtualenv
    - npm config set cache ${NPM_CACHE_DIR} --global
  cache:
    # pip's cache
    - paths:
        - .cache/pip
        - "**/.venv"
    # npm's cache
    - key:
        files:
          - web_client/package-lock.json
      paths:
        - .cache/npm/
    # atari roms cache
    - key:
        files:
          - run.sh
          - environment/requirements.txr
      paths:
        - environment/.atari_roms

build_and_test:
  extends: .base
  script:
    - ./run.sh build
    - ./run.sh lint
    - ./run.sh test

apache_licenses_check:
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker
