stages:
  - lint
  - build
  - test

.base_docker_build:
  image: docker:23.0.1
  services:
    - docker:23.0.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

build_docker:
  stage: build
  needs: []
  extends: .base_docker_build
  script:
    - docker compose build

.base:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - mkdir -p ${PIP_CACHE_DIR}
    - apt-get update
    - apt-get install -y swig python3-opencv libosmesa6-dev patchelf
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  cache:
    # pip's cache
    - paths:
        - .cache/pip
        - "**/.venv"
    # .venv
    - key:
        files:
          - requirements.txt
      paths:
        - .venv

black:
  stage: lint
  extends: .base
  script:
    - black --check --diff .

pylint:
  stage: lint
  extends: .base
  script:
    - pylint --recursive=y .

apache_licenses_check:
  stage: lint
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker

pytest:
  stage: test
  extends: .base
  script:
    - python -m pytest -m --durations=0 -v

