version: "3.7"

services:
  test_environment:
    build:
      context: ./environment
      args:
        BASE_PYTHON_IMAGE: cogment/cogment-verse-python-sdk:${IMAGE_TAG:-local}
    command: poetry run task test

  test_torch_agents:
    build:
      context: torch_agents
      dockerfile: test.dockerfile
      args:
        BASE_PYTHON_IMAGE: cogment/cogment-verse-python-sdk:${IMAGE_TAG:-local}
