version: "3.7"

services:
  torch_agents: &torch_agents
    build:
      context: torch_agents
      dockerfile: gpu.dockerfile
      args:
        BASE_PYTHON_IMAGE: cogment/cogment-verse-python-sdk:${IMAGE_TAG:-local}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              # device_ids: ["0", "1"]
