#!/usr/bin/env bash

# This script acts as a command "menu" for this project.
# - You can list the available commands using `./run.sh commands`
# - You can add a command as a bash function in this file

set -o errexit

ROOT_DIR=$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
RUN_SCRIPT="./$(basename -- "${BASH_SOURCE[0]}")"

### PRIVATE SUPPORT FUNCTIONS ###

function _run_parallel() {
  commands=("$@")
  commands_num="${#commands[@]}"

  # Using GNU parallel to launch the provided commands in parallel and properly handle
  # their output and termination.
  #
  # In particular:
  # - When this process ends, the commands will end (default behavior)
  # - When one of the commands fails everything is stopped (`--halt now,fail=1`)
  # - All the output are printed as they are generated by the command (`-u`)
  # - As many jobs as there are provided commands are ran (`-j "${commands_num}"`)
  #parallel -j "${commands_num}" --retries=2 -u --halt now,fail=1 "${RUN_SCRIPT}" ::: "${commands[@]}"
  parallel -j "${commands_num}" -u --halt now,fail=1 "${RUN_SCRIPT}" ::: "${commands[@]}"
}

function _run_sequence() {
  commands=("$@")

  for command in "${commands[@]}"; do
    "${command}"
  done
}

### GENERIC PUBLIC COMMANDS ###

function commands() {
  all_commands=$(declare -F | awk '{print $NF}' | sort | grep -Ev "^_")
  for command in "${all_commands[@]}"; do
    if [[ ! ("${command}" =~ ^_.*) ]]; then
      printf "%s\n" "${command}"
    fi
  done
}

### PROJECT SPECIFIC PUBLIC COMMANDS ###

function build_python() {
  python -m venv .venv
  # shellcheck disable=SC1091
  source .venv/bin/activate
  pip install -r requirements.txt
  #python -m cogment.generate
  deactivate
}

function mlflow_start() {
  source .venv/bin/activate
  .venv/bin/python -m simple_mlflow
}

function main_start() {
  source .venv/bin/activate
  .venv/bin/python -m main "$@"
}

function experiment() {
  mlflow_start &
  sleep 3
  main_start "+experiment=$@"
}

function main() {
  mlflow_start &
  sleep 3
  main_start "$@"
}

# Docker related functions (to run outside the docker container)
function docker_build() {
    docker build -t local/cogverse .
}

function docker_main() {
    docker run --rm -it --network=host local/cogverse main "$@"
}

function docker_experiment() {
    docker run --rm -it --network=host local/cogverse experiment "$@"
}

function docker_bash() {
    docker run --rm -it --network=host --entrypoint=bash local/cogverse
}

### MAIN SCRIPT ###

available_commands=$(commands)
command=$1
if [[ "${available_commands[*]}" = *"$1"* ]]; then
  shift
  ${command} "$@"
else
  printf "Unknown command [%s]\n" "${command}"
  printf "Available commands are:\n%s\n" "${available_commands[*]}"
  exit 1
fi
