class_name: environments.petting_zoo.environment.HumanFeedbackAtariEnvironment
env_class_name: pettingzoo.atari.pong_v3
port: ${generate_port:environments.petting_zoo.environment.HumanFeedbackAtariEnvironment}
