class_name: environments.pettingzoo.environment.HumanFeedbackAtariEnvironment
env_class_name: pettingzoo.atari.pong_v3
port: ${generate_port:environments.pettingzoo.environment.HumanFeedbackAtariEnvironment}
