# @package _global_.services.environment
class_name: environments.overcooked_adapter.OvercookedEnvironment
env_name: overcooked
port: ${generate_port:environments.overcooked_adapter.OvercookedEnvironment}

layout: centre_pots
turn_based: True
num_players: 2
