class_name: environments.overcooked_adapter.OvercookedEnvironment
env_name: overcooked-turn-based
port: ${generate_port:environments.overcooked_adapter.OvercookedEnvironment}

layout: cramped_room
turn_based: True
