class_name: environments.pettingzoo_adapter.HumanFeedbackAtariEnvironment
env_class_name: pettingzoo.atari.pong_v3
port: ${generate_port:environments.pettingzoo_adapter.HumanFeedbackAtariEnvironment}
