{
 "title": "Model Registry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avg model publish duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job)(rate(model_registry_publish_version_seconds_sum[5m])/rate(model_registry_publish_version_seconds_count[5m]))",
     "legendFormat": "client = {{ job }}"
    }
   ]
  },
  {
   "title": "Avg model retrieve duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job, cached) (rate(model_registry_retrieve_version_seconds_sum[5m])/rate(model_registry_retrieve_version_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "# Published Model Version",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job)(model_registry_publish_version_seconds_count)",
     "legendFormat": "client = {{job}}"
    },
    {
     "expr": "sum by (model_id)(model_registry_publish_version_seconds_count)",
     "legendFormat": "model = {{model_id}}"
    }
   ]
  }
 ]
}