# @package _global_
defaults:
  - override /services/actor:
      - random
  - override /services/environment: connect_four

run:
  class_name: runs.play.PlayRun
  num_trials: 5
  seed: 12
  observer: True
  players:
    - name: player_1
      implementation: actors.random_actor.RandomActor
    - name: player_2
      implementation: actors.random_actor.RandomActor
