class_name: runs.play.PlayRun
num_trials: 5
seed: 12
players:
  - name: player_1
    implementation: client
  - name: player_2
    implementation: actors.overcooked_bc.SimpleBCActor
    # agent_config:
    #   model_id: silly_whitehat_0_model
    #   model_iteration: -1
    #   model_update_frequency: ~
